# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "tb4"
  limits:
    linear: [0.5, 0.75] # velocity, acceleration
    angular: [0.6, 2.0] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.3 # radius in m
    vicinity: 0.5 # radius in m
  reversible: True # whether robots in this fleet can reverse
  battery_system:
    voltage: 12.0 # V
    capacity: 24.0 # Ahr
    charging_current: 5.0 # A
  mechanical_system:
    mass: 20.0 # kg
    moment_of_inertia: 10.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: 10.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
  actions: []
  finishing_request: "nothing" # [park, charge, nothing]
  responsive_wait: False # Should responsive wait be on/off for the whole fleet by default? False if not specified.
  robots:
    tb4:
        charger: "tb4_start"
        # For robot API
        map: "L1"
        prefix: ""
        target_frame: "map"
        from_frame: "base_link"

conversions:
  reference_coordinates:
    L1:
      rmf: [[0.1, -1.2494],
            [7.5464, -0.6497],
            [10.3451, -5.3975],
            [1.7492, -7.4465]]
      tb4: [[-5.422642707824707, 3.07148814201355],
            [2.0564370155334473, 3.6545846462249756],
            [4.780905723571777, -1.036746859550476],
            [-3.804450511932373, -3.1021950244903564]]

  map:
    # rmf to tb4
    L1: 'map'
